apiVersion: v1
kind: Secret
metadata:
  name: my-database-secret
  # workaround for https://github.com/fabric8io/fabric8-maven-plugin/issues/1791
  annotations: {}
stringData:
  user: luke
  password: secret
